---
- name: Testing simple roles
  hosts: servera
  vars:
    username: albert
    private_value: hello world
  #vars_files:
  #  vars/data.yml
  tasks:
    - name: Display Public info
      debug:
        msg: You are {{ username }}

    - name: Private data
      debug:
        msg: Private info internal use -> {{ private_value }}

    - name: Copying File
      copy:
        src: files/role.txt
        dest: ./role.txt

    - name: using template
      template:
        src: templates/role.j2
        dest: ./role-template.cfg
...
