- name: testing parallelism and rolling update
  hosts: all
  serial: 1
  tasks:
    - name: T1
      debug:
        msg: Task 1

    - name: T2
      command: sleep 5

    - name: T3
      debug:
        msg: Task 3
