- name: first playbook
  gather_facts: false
  hosts: servera
  tasks:
    - name: Task 1
      debug:
        msg: Hi, your interface ip is # {{ ansible_facts.default_ipv4.address }}
    
    - name: Task 2
      debug:
        msg: |
          command: ls
      changed_when: false
