- name: testing delegation of facts
  hosts: servera.lab.example.com
  gather_facts: true
  tasks:
    - name: Gather facts
      setup:
      delegate_to: serverb.lab.example.com
      delegate_facts: true

    - name: display hostvars
      debug:
        msg:
          - you are in {{ ansible_facts.fqdn }}
          - serverb is {{ hostvars['serverb.lab.example.com']['ansible_facts']['fqdn'] }}
