- name: adsf
  hosts: all
  order: sorted
  gather_facts: false
  become: true
  pre_tasks:
    - name: Gathering Facts
      setup:

    - name: T1
      debug:
        msg: Task 1

    - name: T2
      become: false
      debug:
        msg: Task 2

    - name: T3
      debug:
        msg: Task 3

