- name: testing facts delegation
  hosts: servera.lab.example.com
  #gather_facts: false
  tasks:
    - name: display hostvars
      debug:
        var: hostvars['servera.lab.example.com']['ansible_facts']['fqdn']

    - name: gather facts
      setup:
      delegate_to: serverb.lab.example.com
      delegate_facts: true

    - name: display servera facts
      debug:
        var: hostvars['servera.lab.example.com']['ansible_facts']['all_ipv4_addresses']

    - name: display serverb facts
      debug:
        var: hostvars['serverb.lab.example.com']['ansible_facts']['all_ipv4_addresses']
